compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[[d1_databases]]
binding = "DB"
database_name = "d1-kysely-demo"
database_id = "0c7970d2-0ec2-4ece-ac1d-5654517c201e"