compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[[d1_databases]]
binding = "DB"
database_name = "D1_KYSELY"
database_id = "59df5d04-7d1c-4e66-afce-434e7ef1e502"
